version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: services_go/cmd/auth/Dockerfile
    ports:
      - "8081:8080"
      - "50051:50051"
    volumes:
      - /root/db-server:/usr/src/app/
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    name: main
    driver: bridge
