import random

# Lists of first names and last names
first_names = [
    "Lê",
    "Đỗ",
    "Nguyễn",
    "Lê",
    "Chu",
    "Nguyễn",
    "Vũ",
    "Đặng",
    "Nguyễn",
    "Nguyễn",
    "Đỗ",
    "Nguyễn",
    "Trần",
    "Phạm",
    "Trần",
    "Lê",
    "Lê",
    "Nguyễn",
    "Nguyễn",
    "Ngô",
    "Nguyễn",
    "Đặng",
    "Hoa",
    "Nguyễn",
    "Nguyễn",
    "Chử",
    "Hoàng",
    "Phan",
    "Nguyễn",
    "Đỗ",
    "Phan",
    "Bùi",
    "Trần",
    "Mai",
]

last_names = [
    "Ngọc Quý",
    "Minh Đức",
    "Bảo Quốc",
    "Tuấn Anh",
    "Quang Dần",
    "Quốc Tuấn",
    "Như Thành",
    "Thanh Tùng",
    "Thế Anh",
    "Dũng Quân",
    "Đức Anh",
    "Phương Linh",
    "Văn Tiến",
    "Tiến Đạt",
    "Ngọc Khiêm",
    "Phương Nam",
    "Hoàng Nguyên",
    "Đức Long",
    "Mạnh Việt",
    "Quang Trường",
    "Quang Mạnh Dũng",
    "Quang Hưng",
    "Đỗ Tùng Dương",
    "Hải Dương",
    "Văn Thành",
    "Văn Minh",
    "Kim Minh",
    "Thị Hồng Linh",
    "Thị Liêm",
    "Thị Xuân",
    "Thành Thắng",
    "Minh Quân",
    "Việt Hùng",
    "Thanh Minh",
]


def name_generator():
    return f"{random.choice(first_names)} {random.choice(last_names)} {random.randint(100, 999)}"
