# # -*- coding: utf-8 -*-
# # Generated by the protocol buffer compiler.  DO NOT EDIT!
# # source: auth.proto
# # Protobuf Python Version: 4.25.1
# """Generated protocol buffer code."""
# from google.protobuf import descriptor as _descriptor
# from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import symbol_database as _symbol_database
# from google.protobuf.internal import builder as _builder
# # @@protoc_insertion_point(imports)

# _sym_db = _symbol_database.Default()




# DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x05proto\"-\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05roles\x18\x02 \x03(\t\"l\n\x0eVerifyResponse\x12-\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1f.proto.VerifyResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32J\n\x0b\x41uthService\x12;\n\nVerifyRole\x12\x14.proto.VerifyRequest\x1a\x15.proto.VerifyResponse\"\x00\x42\x06Z\x04./pbb\x06proto3')

# _globals = globals()
# _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
# _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
# if _descriptor._USE_C_DESCRIPTORS == False:
#   _globals['DESCRIPTOR']._options = None
#   _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
#   _globals['_VERIFYRESPONSE_DATAENTRY']._options = None
#   _globals['_VERIFYRESPONSE_DATAENTRY']._serialized_options = b'8\001'
#   _globals['_VERIFYREQUEST']._serialized_start=21
#   _globals['_VERIFYREQUEST']._serialized_end=66
#   _globals['_VERIFYRESPONSE']._serialized_start=68
#   _globals['_VERIFYRESPONSE']._serialized_end=176
#   _globals['_VERIFYRESPONSE_DATAENTRY']._serialized_start=133
#   _globals['_VERIFYRESPONSE_DATAENTRY']._serialized_end=176
#   _globals['_AUTHSERVICE']._serialized_start=178
#   _globals['_AUTHSERVICE']._serialized_end=252
# # @@protoc_insertion_point(module_scope)
