# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_mart.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_mart.proto\x12\x05proto\" \n\x12GetDataMartRequest\x12\n\n\x02id\x18\x01 \x01(\t\"v\n\x13GetDataMartResponse\x12\x32\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32$.proto.GetDataMartResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32Y\n\x0f\x44\x61taMartService\x12\x46\n\x0bGetDataMart\x12\x19.proto.GetDataMartRequest\x1a\x1a.proto.GetDataMartResponse\"\x00\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_mart_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_GETDATAMARTRESPONSE_DATAENTRY']._options = None
  _globals['_GETDATAMARTRESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_GETDATAMARTREQUEST']._serialized_start=26
  _globals['_GETDATAMARTREQUEST']._serialized_end=58
  _globals['_GETDATAMARTRESPONSE']._serialized_start=60
  _globals['_GETDATAMARTRESPONSE']._serialized_end=178
  _globals['_GETDATAMARTRESPONSE_DATAENTRY']._serialized_start=135
  _globals['_GETDATAMARTRESPONSE_DATAENTRY']._serialized_end=178
  _globals['_DATAMARTSERVICE']._serialized_start=180
  _globals['_DATAMARTSERVICE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
