version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${CONSOLE_PORT}:${CONSOLE_PORT}"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${USER}
      MINIO_ROOT_PASSWORD: ${PASSWORD}
    command: server --console-address ":${CONSOLE_PORT}" /data
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - main

volumes:
  minio_storage: {}

networks:
  main:
    name: main
    driver: bridge
