version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
      - PGDATA=/var/lib/postgresql/pgdata
    volumes:
      - postgres:/var/lib/postgresql/pgdata
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - main

volumes:
  postgres:


networks:
  main:
    name: main
    driver: bridge
